"""add tax_rate to invoices

Revision ID: 2cb43fdbd7f0
Revises: e9a5105a168b
Create Date: 2026-09-16 22:17:28.913682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb43fdbd7f0'
down_revision = 'e9a5105a168b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False,server_default='0'))
        batch_op.create_index(batch_op.f('ix_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_unique_constraint('uq_invoice_business_number', ['business_id', 'invoice_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('uq_invoice_business_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_invoices_customer_id'))
        batch_op.drop_column('tax_rate')

    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_owner_id'))

    # ### end Alembic commands ###
